### PR TITLE
Fix some of AVIF 10 bit HDR contents preview issues

### LINKED ISSUE #15: After install via brew and qlmanage reload cache, the thumbnail updated, but become gray
image
image

first origin heif, second avif

### PR DESCRIPTION
**Pull request by dreampiggy**
This fix #15 

### Changes
Update to directly use SDWebImageAVIFCoder v0.11.1
Update to CocoaPods
Update to use libdav1d instead of libaom for AVIF Decoding

### CODE REVIEW

File: AVIFQuickLook/GeneratePreviewForURL.m [hunk 1]
```diff
@@ -18,7 +18,9 @@ OSStatus GeneratePreviewForURL(void *thisInterface, QLPreviewRequestRef preview,
     @autoreleasepool {
         
         NSString *path = [(__bridge NSURL *)url path];
-        CGImageRef cgImgRef = [AVIFDecoder createAVIFImageAtPath:path];
+        NSData *data = [NSData dataWithContentsOfFile:path];
```
Comment (dreampiggy) [inline AVIFQuickLook/GeneratePreviewForURL.m:21]: Use `dataWithContentsOfURL:` is simple
